[versions]
agp = "8.13.0"
okhttp = "5.1.0"
sdpAndroid = "1.1.1"

[libraries]
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
sdp-android = { module = "com.intuit.sdp:sdp-android", version.ref = "sdpAndroid" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }

